### ISSUE TITLE
Could not determine the dependencies of task ':freerasp-react-native:compileDebugAidl'

### ISSUE THREAD

**Issue by virenradadiya** [talsec/Free-RASP-ReactNative#6] opened 2023-02-13 09:01 UTC
**Describe the bug**
I am having an error like Required by the project: free-rasp-react-native while building the app after installing the dependency.

**Screenshots**
error Screenshots
![image](https://user-images.githubusercontent.com/30589064/218414120-56996230-5f04-4aa5-8f5f-4823642540e4.png)

My build.Gradle
![image](https://user-images.githubusercontent.com/30589064/218414627-e7ce1791-0143-4931-aba8-5069d49c68a9.png)

**Comment by tompsota** [comment] 2023-02-14 08:05
Hello @virenradadiya,

Thanks for opening your first issue. 

The build failure might be caused by the version of React Native you are using in the project. 

Please try to update React Native to a higher patch version as explained here: https://github.com/facebook/react-native/issues/35210 

Let us know if that helped.


Best,

Tomas, Talsec developer

**Comment by msikyna** [comment] 2023-02-21 09:46
Hello @virenradadiya ,

did you try updating React Native to a higher patch version as @tompsota suggested?
Did that help?

Kind regards,
Matúš, Talsec dev

**Comment by muqeet98** [comment] 2023-02-21 11:33
@virenradadiya Fixed Issue with these steps:
1. updated React Native version to 0.69.7
2. Change syntax of the maven library.
`allprojects {
    repositories {
         exclusiveContent {
       // We get React Native's Android binaries exclusively through npm,
       // from a local Maven repo inside node_modules/react-native/.
       // (The use of exclusiveContent prevents looking elsewhere like Maven Central
       // and potentially getting a wrong version.)
       filter {
           includeGroup "com.facebook.react"
       }
       forRepository {
           maven {
               url "$rootDir/../node_modules/react-native/android"
           }
       }
         }
    //    mavenCentral()
        google()
        // mavenCentral()

        //   maven {url =
// uri("https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp")}
// maven {url "https://developer.huawei.com/repo/"}

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
            maven {
      url "https://cashshield-sdk.s3.amazonaws.com/release/"
    }
            mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
 jcenter() // <-- Add this
        maven { url 'https://www.jitpack.io' }
       
        
        // maven { url 'https://dl.bintray.com/ironsource-mobile/android-sdk' }
        //**Change to given below.**
        maven { url 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp'}
        maven { url 'https://developer.huawei.com/repo/'}
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo'}
        //  maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
        // maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }

         
    }
}`

**Comment by muqeet98** [comment] 2023-02-21 11:39
@virenradadiya Fixed Issue with these steps:
 1. updated React Native version to 0.69.7

2 .Change syntax of the maven library.
Example:
Change
` maven{url = uri("https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp")}
`
with 
` maven { url 'https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp'}`

**Comment by muqeet98** [comment] 2023-02-21 11:39
![Screenshot 2023-02-21 at 4 25 48 PM](https://user-images.githubusercontent.com/40955420/220335245-b5b86510-79ae-4b17-8a25-e2896ba1c47b.png)

**Comment by msikyna** [comment] 2023-04-19 08:18
Hello @virenradadiya ,

were you able to solve the issue?
NB: a new version has been released.

Kind regards,
Talsec team

**Comment by tompsota** [comment] 2023-04-25 06:56
Hello @wellespaiva-dev,

what versions of `react-native` and `freerasp-react-native` are you using?

Best,
Tomas, Talsec developer

**Comment by wellespaiva-dev** [comment] 2023-04-26 15:02
"react-native": "0.69.5",
"freerasp-react-native": "2.0.1",


I managed to fix the error with @muqeet98 solution, but I'm getting another error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons

I am getting the error when using the function useFreeRasp(config, actions);

**Comment by tompsota** [comment] 2023-04-26 15:41
@wellespaiva-dev,

Glad to hear you fixed the first issue.

You see the other error because useFreeRasp is a hook itself and cannot be called inside another hook. You can either move useFreeRasp outside the useEffect or alternatively remove the provided hook and start freeRASP in your useEffect instead. Such useEffect would look like this:

```
  useEffect(() => {
    setThreatListeners(actions);
    talsecStart(config);

    return () => {
      removeThreatListeners();
    };
  }, []);
```

You can import all methods from `freerasp-react-native` module.

The return part is optional, but highly recommended.


Best,
Tomas, Talsec developer

**Comment by wellespaiva-dev** [comment] 2023-05-17 05:15
Hello @talsec-app, the proposal worked! Thank you very much.

A doubt! Is there any documentation on what each config represents? Is it all necessary to work?

Hugs.

**Comment by tompsota** [comment] 2023-05-18 12:13
Hi @wellespaiva-dev,

 The keys in config object are explained here: https://github.com/talsec/Free-RASP-ReactNative#the-configuration-object-should-consist-of. If you are developing only for Android, you don't need to specify config for iOS and vice versa. 

Does this answer your question?

Best,
Tomas, Talsec developer.

**Comment by wellespaiva-dev** [comment] 2023-05-20 20:33
Hello @talsec-app  I'm building a build on ios and sending it to testFlight, but I'm getting this error when opening the app: Library not load: @rpath/Talsec Runtime.framework/Talsec Runtime


NOTE: The error does not happen in debug mode

**Comment by wellespaiva-dev** [comment] 2023-05-23 18:23
@talsec-app

<img width="349" alt="Captura de Tela 2023-05-23 às 15 18 02" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/f32d860c-519d-4a44-b584-1e6c54435fef">
<img width="391" alt="Captura de Tela 2023-05-23 às 15 20 58" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/c620e1bb-2d1b-4866-a735-1b5dedc9b11b">

**Comment by msikyna** [comment] 2023-05-24 05:19
Hello @wellespaiva-dev ,

is the TalsecRuntime.xcframework in that folder a symlink, or is it a folder? In the new version, we have removed the dependency on the symlink and integration script switching between the dev and release version of the SDK. You have to remove also the integration script:

1. Open up the .**xcworkspace** file
2. Go to **Target** -> **Build Phases** -> **Link Binary With Libraries**
3. Remove **TalsecRuntime.xcframework**
4. On top bar select **Product** -> **Scheme** -> **Edit Scheme...**
5. On the left side select **Build** -> **Pre-actions**
6. Find integration script and click trash icon on the right side to remove it
7. Update freeRASP. If you are getting any errors, check that in `node_modules/freerasp-react-native/ios, TalsecRuntime.xcframework` is a folder, not a symlink. If it is a symlink, remove it and reinstall the module.
8. run `pod install`

Please, let us know if it helps.

**Comment by wellespaiva-dev** [comment] 2023-05-25 18:10
Hi @talsec-app,

Regarding the first question, TalsecRuntime.xcframework is a folder (as shown in the image below). The version of freerasp-react-native is more current, 2.0.1.

<img width="320" alt="Captura de Tela 2023-05-24 às 17 06 11" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/e49f9717-7e1b-4c4a-986c-a350b160c22b">

In the second case, TalsecRuntime.xcframework is not found in Target -> Build Phases -> Link Binary With Libraries, as shown in the images below.

<img width="904" alt="Captura de Tela 2023-05-25 às 15 03 43" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/45ac78d5-6d6f-4943-a5df-e7a6ca2482cd">

<img width="904" alt="Captura de Tela 2023-05-25 às 15 04 19" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/58eddb6f-9540-4ed8-a2c7-e4fa78484486">

Thirdly, I didn't find that integration script you guys mentioned. The images below show the only scripts that already existed before the implementation of the library.

<img width="916" alt="Captura de Tela 2023-05-24 às 17 01 46" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/749412db-f3a2-409d-8f6d-15c4b5c48769">

<img width="921" alt="Captura de Tela 2023-05-24 às 17 04 01" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/c1de6aad-8a97-4abf-905a-55a7e9fd35cd">

Anyway, I'm going to leave the crashlog file that testFlight generates when there is a crash signal in the application.

[testflight_feedback.zip](https://github.com/talsec/Free-RASP-ReactNative/files/11568008/testflight_feedback.zip)

I'm waiting for a possible solution. Hugs.

**Comment by wellespaiva-dev** [comment] 2023-05-26 02:04
Hi @talsec-app,

I have updated the library to 2.0.2 and the error persists.

**Comment by msikyna** [comment] 2023-05-26 07:55
Hello @wellespaiva-dev ,

did you run pod install in the iOS directory after adding (or upgrading) the plugin?
If yes, could we try:
1. Delete DerivedData folder and make a clean build
2. Place the TalsecRuntime.xcframework in the Embedded Frameworks (Target -> General -> Frameworks, Libraries, and Embedded Content) manually, then click Embed & Sign

**Comment by wellespaiva-dev** [comment] 2023-05-28 16:17
Hi, @talsec-app


I tried to do what you asked and another error occurred! In this error I can't even run the app in debug mode.

Here is the evidence below:

<img width="1183" alt="Captura de Tela 2023-05-28 às 13 16 45" src="https://github.com/talsec/Free-RASP-ReactNative/assets/69151464/fa7691fb-a8d0-4322-b201-27d71ef9d32a">

**Comment by tompsota** [comment] 2023-05-29 11:56
Hi @wellespaiva-dev,

Can you try following?
1. Ensure that you see the `TalsecRuntime.cxframework` also in **Build Phases > Link Binary With Libraries**:
<img width="562" alt="Screenshot 2023-05-29 at 13 41 27" src="https://github.com/talsec/Free-RASP-ReactNative/assets/72520867/8d463be0-8965-4d82-b79f-df83a5cd97f0">

If not, please add it there as well:
<img width="402" alt="Screenshot 2023-05-29 at 13 38 10" src="https://github.com/talsec/Free-RASP-ReactNative/assets/72520867/9b20b71d-8196-41fc-91fa-202ba264e247">
2. Go to `<yourProject>/ios/Pods/Target Support Files/Pods-<yourProject>`
3. Open `Pods-<yourProject>-frameworks-Debug-input-files.xcfilelist` and delete line that contains `TalsecRuntime`
4. Do the same in these files in that folder as well (there should be one line in each file):
- `Pods-<yourProject>-frameworks-Debug-output-files.xcfilelist`
- `Pods-<yourProject>-frameworks-Release-input-files.xcfilelist`
- `Pods-<yourProject>-frameworks-Release-output-files.xcfilelist`
5. Try to run the app. The error should be gone.

If the suggestion above didn't help, can you please answer these questions?
1. Does this error happen only on TestFlight? E.g. does the app work when you run it in release mode locally?
2. Is this a clean installation or are you upgrading freeRASP from 1.x.x to 2.x.x?
3. I noticed that the first Run Script deletes the info.plist file. Although we did not encounter any issues with that so far, it seems suspicious to me. Is there any specific reason why you added that script? 

Cheers,

Tomas, Talsec developer

**Comment by wellespaiva-dev** [comment] 2023-05-29 20:03
Hi @talsec-app,

I did what you asked and it worked for the problem above, but it keeps closing the app in release versions.

1 - Does this error happen only on TestFlight? E.g. does the app work when you run it in release mode locally?
R: There is no local release version, versions are generated via xcode and uploaded directly to TestFlight. Running locally in debug mode the error does not happen.

2 - Is this a clean installation or are you upgrading freeRASP from 1.x.x to 2.x.x?
R: When I started the lib it was in version 2.0.1, and I updated it to 2.0.2. I uninstalled and reinstalled and the error persisted. The error occurs since version 2.0.1.


3 - I noticed that the first Run Script deletes the info.plist file. Although we did not encounter any issues with that so far, it seems suspicious to me. Is there any specific reason why you added that script?
R: The application contains two targets, so this script refers to the "react-native-config" library, where it checks which target was started to know which .env file to use.

**Comment by tompsota** [comment] 2023-05-30 08:17
Hi @wellespaiva-dev,

Can you try following:
1. Go to **Product > Scheme > Edit Scheme...**
2. On left side select **Run** and change Build Configuration to Release
3. Run the app

Do you see the error now? This will help us to determine if the problem is in the implementation or only on TestFlight.

Best,
Tomas, Talsec developer

**Comment by msikyna** [comment] 2023-07-19 05:57
Hello @wellespaiva-dev, 
did you manage to solve the issue? Does it still persist in v3.1.0?

Kind regards,
Talsec team

**Comment by tompsota** [comment] 2023-09-21 13:48
Closing the issue due to inactivity. Feel free to reopen if there are any updates.

**Closed by tompsota** 2023-09-21 13:48 UTC
Labels: bug, waiting for response
